# Homebrew formula template — kept as a manual fallback. The real formula is
# auto-generated by GoReleaser on each release and pushed to hadihonarvar/homebrew-tap.
#
# Tap and install:
#   brew tap hadihonarvar/tap
#   brew install flock

class Flock < Formula
  desc "Orchestrate open-weight LLMs across your machines"
  homepage "https://github.com/hadihonarvar/flock"
  license "Apache-2.0"
  version "0.0.0" # placeholder; GoReleaser sets this

  # Optional but recommended dependency: llama.cpp ships `rpc-server` +
  # `llama-server`, which Flock launches when you `flock shard create` a
  # model across multiple machines. Single-node Flock works without it.
  # `flock doctor` warns when rpc-server is missing on the PATH.
  depends_on "llama.cpp" => :recommended

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hadihonarvar/flock/releases/download/v#{version}/flock-darwin-arm64.tar.gz"
      sha256 "REPLACE_WITH_REAL_SHA256"
    else
      url "https://github.com/hadihonarvar/flock/releases/download/v#{version}/flock-darwin-amd64.tar.gz"
      sha256 "REPLACE_WITH_REAL_SHA256"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/hadihonarvar/flock/releases/download/v#{version}/flock-linux-arm64.tar.gz"
      sha256 "REPLACE_WITH_REAL_SHA256"
    else
      url "https://github.com/hadihonarvar/flock/releases/download/v#{version}/flock-linux-amd64.tar.gz"
      sha256 "REPLACE_WITH_REAL_SHA256"
    end
  end

  def install
    bin.install "flock"
  end

  test do
    system "#{bin}/flock", "version"
  end
end
