apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flock-data
  namespace: poc-flock
  labels:
    app: flock
    autopoc.io/project: flock
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
